version: '3.8'

services:
  todo_backend:
    build: .
    container_name: todo_laravel_app
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
      - todo_vendor_data:/var/www/html/vendor
    depends_on:
      - todo_database

  todo_database:
    image: mysql:8.0
    container_name: todo_mysql_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: todolist_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - todo_db_data:/var/lib/mysql

  ping_worker:
    build: 
      context: ./node_worker
    container_name: my_node_worker
    restart: unless-stopped
    depends_on:
      - todo_backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: todo_database
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - todo_database
volumes:
  todo_db_data:
  todo_vendor_data: